# Generated by Django 4.0.4 on 2022-05-03 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='DateOfJoining',
            field=models.DateField(auto_now_add=True),
        ),
    ]
