# Generated by Django 4.0.4 on 2022-05-07 09:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('EmployeeApp', '0002_alter_employee_dateofjoining'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Departments',
        ),
        migrations.AlterField(
            model_name='employee',
            name='EmployeeName',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
