# Generated by Django 4.0.4 on 2022-05-07 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0003_delete_departments_alter_employee_employeename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='Department',
        ),
    ]
