# Generated by Django 4.0.4 on 2022-05-12 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0014_alter_employee_employeename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='EmployeeName',
            field=models.CharField(default=None, max_length=150),
            preserve_default=False,
        ),
    ]
