# Generated by Django 4.0.4 on 2022-05-12 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0015_alter_employee_employeename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='EmployeeName',
            new_name='EmployeeName_id',
        ),
    ]
