# Generated by Django 4.0.4 on 2022-05-12 02:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0016_rename_employeename_employee_employeename_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='EmployeeName_id',
            new_name='EmployeeName',
        ),
    ]
