# Generated by Django 4.0.4 on 2022-05-12 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0018_bank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='Adress',
            field=models.CharField(max_length=300),
        ),
    ]
