# Generated by Django 4.0.4 on 2022-05-12 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0019_alter_bank_adress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bank',
            name='State',
        ),
    ]
