# Generated by Django 4.0.4 on 2022-05-12 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EmployeeApp', '0020_remove_bank_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bank',
            name='Adress',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='Branch',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='City',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='Country',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_n',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='bank_num',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='bank',
            name='country_num',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
